global_planner_node:
  ros__parameters:
    map_topic: "earth_rover/persistent_map"
    target_topic: "earth_rover/target_waypoint"
    global_path_topic: "earth_rover/global_path"
    global_planner_valid_topic: "earth_rover/global_planner_valid"
    map_frame: "map"
    base_frame: "base_link"
    from_ll_service: "/fromLL"
    replan_min_period_s: 2.0
    occupied_cost_threshold: 55.0
    unknown_cell_cost: 20.0
    connectivity: 8
    tf_lookup_timeout_s: 0.2
